### ISSUE TITLE
Error "execution reverted"

### ISSUE THREAD

**Issue by dappstatus** [lessmore92/php-erc20#2]
I try to use "$token->name()" in a loop. It works most of the time. But sometimes i run into an error "execution reverted". 
Any idea how to handle this?

This is an example transaction / address where it happens.
Transaction: https://etherscan.io/tx/0x15bc9ee5c237f381dca60c1be0e8fee470a1491c5fe62b967d9e5cf3d1c698d0
Address: 0x656acfd86be535353f0a08a327368ccf7304e819

![111](https://user-images.githubusercontent.com/42303143/109835493-36ad9080-7c7e-11eb-9eb5-4fe37cf83973.JPG)
![222](https://user-images.githubusercontent.com/42303143/109835510-390fea80-7c7e-11eb-9d1b-01da6bb79b92.JPG)

**Comment by lessmore92** [comment]
0x656acfd86be535353f0a08a327368ccf7304e819 seems it is not standard ERC20 contract, that not support `name` method

**Comment by dappstatus** [comment]
The contract is 0x15bc9ee5c237f381dca60c1be0e8fee470a1491c5fe62b967d9e5cf3d1c698d0
0x656acfd86be535353f0a08a327368ccf7304e819 is the address that is used to get the token name from.

**Comment by dappstatus** [comment]
If you check the logs of that contract https://etherscan.io/tx/0x15bc9ee5c237f381dca60c1be0e8fee470a1491c5fe62b967d9e5cf3d1c698d0
You can see it has 5 logs.
I have a loop for the logs to check all the names of each log entry. The first 3 log entries work. Number 4 with the log address 0x656acfd86be535353f0a08a327368ccf7304e819 shows the error.

**Comment by lessmore92** [comment]
`0x15bc9ee5c237f381dca60c1be0e8fee470a1491c5fe62b967d9e5cf3d1c698d0` is Transaction ID and Contarct `0x656acfd86be535353f0a08a327368ccf7304e819`

**Comment by dappstatus** [comment]
Oh you are right. It's late here :D
Anyways. Any idea how i can handle this in my loop? Since the first 3 logs work and the error only appears on the 4th log address. You say it's not and ERC20 standard that supports name, how can i avoid the error in that case?

**Comment by lessmore92** [comment]
As simple solution you can catch the `RuntimeException` Exception
