### ISSUE TITLE
I can't understand the parameters.

### ISSUE THREAD

**Issue by BeycanDeveloper** [lessmore92/php-erc20#6]
Hello, I can't understand the parameters, why is the owner, what's going on with myapp, and there is a to address, I'm very confused please help.

**Comment by BeycanDeveloper** [comment]
My problem was solved, I made the transfer. I entered the "from" address in the addresses you specified as Owner and myApp, and I entered the "to" address in the other parameter. But I still don't understand why there are two parameters, owner and myapp. I would expect it to be "from", "to", "amount".

**Comment by lessmore92** [comment]
The `transfer(string $from, string $to, float $amount)` function have 3 parameters.
The `transferFrom(string $spender, string $from, string $to, float $amount)` have 4 params and used for transfer token using DAPP, on behalf of other user(s).

I think in your case, you need to use `transfer`.
